rtdip/core

- environment.yml
> Fix to Mkdocs String Package

- .github/workflows/release.yml
- .github/workflows/test.yml
> Add Mamba for Conda Installation

- .github/workflows/test.yml
> Updates for Mamba in CI/CD

- .github/release.yml
- README.md
- src/api/README.md
> Add badges to Readme

- docs/CNAME
> Add CNAME file to docs for custom domain www.rtdip.io

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/security_vulnerability.md
- .github/workflows/develop.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- docs/getting-started/installation.md
- src/api/Dockerfile
> Update tests for multiple versions of Python

- .devcontainer/devcontainer.json
Signed-off-by: cching95 <73163191+cching95@users.noreply.github.com>
> updated devcontainer.json

- setup.py
Signed-off-by: NooraKubati <noora.kubati@shell.com>
> Removal of packaging legacy version dependency

- .github/workflows/test.yml
- .gitignore
Signed-off-by: GBBBAS <42962356+GBBBAS@users.noreply.github.com>
> Add OS Matrix to CI Tests

- .github/workflows/test.yml
> Remove OS matrix from Actions due to Boost

- environment.yml
> Upgrade dbx

- docs/blog/rtdip_ingestion_pipelines.md
- environment.yml
- setup.py
> Add Pipelines as Extras libraries to setup

- src/api/Dockerfile
> Fix for docker build error

- src/api/Dockerfile
> Fix for docker build

- .github/workflows/sonarcloud.yml
- .github/workflows/test.yml
> Github Actions Sonarcloud Refactor for forked branches

- .devcontainer/devcontainer.json
- .vscode/settings.json
- docs/assets/extra.css
- docs/blog/overview.md
- docs/blog/rtdip_ingestion_pipelines.md
- docs/macros.py
- docs/sdk/code-reference/pipelines/transformers/spark/json_to_opcua.md
- docs/sdk/code-reference/pipelines/transformers/spark/opc_publisher_json_to_opcua.md
- docs/sdk/pipelines/components.md
- docs/sdk/pipelines/framework.md
- docs/sdk/queries/functions.md
- mkdocs.yml
- src/sdk/python/rtdip_sdk/pipelines/transformers/__init__.py
- src/sdk/python/rtdip_sdk/pipelines/transformers/spark/opc_publisher_json_to_opcua.py
- tests/docs/test_macros.py
- tests/sdk/python/rtdip_sdk/pipelines/transformers/spark/test_opc_publisher_json_to_opcua.py
> Documentation Updates

- .github/workflows/sonarcloud.yml
- docs/macros.py
- docs/sdk/pipelines/jobs.md
- mkdocs.yml
- setup.py
> Package Setup Update for Data Files

- docs/sdk/code-reference/pipelines/destinations/spark/delta_merge.md
- docs/sdk/pipelines/components.md
- mkdocs.yml
- src/sdk/python/rtdip_sdk/pipelines/destinations/__init__.py
- src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
- tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_delta.py
- tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_delta_merge.py
> Delta Merge Destination Component

- docs/sdk/code-reference/pipelines/utilities/spark/adls_gen2_spn_connect.md
- docs/sdk/pipelines/components.md
- mkdocs.yml
- src/sdk/python/rtdip_sdk/pipelines/utilities/spark/adls_gen2_spn_connect.py
- tests/sdk/python/rtdip_sdk/pipelines/utilities/spark/test_adls_gen2_spn_connect.py
> Spark ADLS Gen2 Service Principal Connect Utility

- docs/sdk/code-reference/pipelines/secrets/azure_key_vault.md
- docs/sdk/pipelines/components.md
- environment.yml
- mkdocs.yml
- setup.py
- src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/constants.py
- src/sdk/python/rtdip_sdk/pipelines/secrets/__init__.py
- src/sdk/python/rtdip_sdk/pipelines/secrets/azure_key_vault.py
- tests/sdk/python/rtdip_sdk/pipelines/secrets/test_azure_key_vault_secrets.py
> Azure Key Vault Secret Component

- src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
- src/sdk/python/rtdip_sdk/pipelines/destinations/spark/pcdm_to_delta.py
- src/sdk/python/rtdip_sdk/pipelines/destinations/spark/rest_api.py
- tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_pcdm_to_delta.py
Update to foreachBatch method signatures to allow batch and streaming code to use the same methods.
> Delta Batch Updates

- .github/workflows/sonarcloud_reusable.yml
- .github/workflows/test.yml
- .vscode/settings.json
- environment.yml
- setup.py
- src/sdk/python/rtdip_sdk/_sdk_utils/__init__.py
- src/sdk/python/rtdip_sdk/_sdk_utils/compare_versions.py
- src/sdk/python/rtdip_sdk/functions/metadata.py
- src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/models.py
- src/sdk/python/rtdip_sdk/pipelines/destinations/spark/delta_merge.py
- src/sdk/python/rtdip_sdk/pipelines/execute/job.py
- src/sdk/python/rtdip_sdk/pipelines/execute/models.py
- src/sdk/python/rtdip_sdk/pipelines/utilities/aws/s3_bucket_policy.py
- src/sdk/python/rtdip_sdk/pipelines/utilities/spark/configuration.py
- src/sdk/python/rtdip_sdk/pipelines/utilities/spark/delta_table_create.py
- src/sdk/python/rtdip_sdk/pipelines/utilities/spark/delta_table_optimize.py
- tests/sdk/python/rtdip_sdk/_sdk_utils/__init__.py
- tests/sdk/python/rtdip_sdk/_sdk_utils/test_compare_versions.py
- tests/sdk/python/rtdip_sdk/pipelines/destinations/spark/test_delta_merge.py
> Support 3.3.* Pyspark Versions

- .github/workflows/release.yml
- .github/workflows/sonarcloud_reusable.yml
- .github/workflows/test.yml
Updates micromamba github actions parameters due to the new component available from micromamba
> Update for Micromamba Github Actions Parameters

- src/api/requirements.txt
Upgrade FastAPI Package to fix #278
> Upgrade FastAPI Package

- environment.yml
- src/api/Dockerfile
- src/api/requirements.txt
Fixes packages issues for APIs
> Update packages for API Container

- docs/sdk/code-reference/pipelines/sources/spark/iso/pjm_daily_load_iso.md
- docs/sdk/code-reference/pipelines/sources/spark/iso/pjm_historical_load_iso.md
- docs/sdk/pipelines/components.md
- mkdocs.yml
- src/sdk/python/rtdip_sdk/pipelines/_pipeline_utils/iso.py
- src/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/__init__.py
- src/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/pjm_daily_load_iso.py
- src/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/pjm_historical_load_iso.py
- tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_pjm_daily_load_iso.py
- tests/sdk/python/rtdip_sdk/pipelines/sources/spark/iso/test_pjm_historical_load_iso.py
trying again with a newly forked repo + PJM source connector files, documentation & test cases
> Source Component - Energy Domain PJM market

- environment.yml
- src/sdk/python/rtdip_sdk/data_models/storage_objects/__init__.py
- src/sdk/python/rtdip_sdk/data_models/storage_objects/utils.py
- src/sdk/python/rtdip_sdk/pipelines/utilities/aws/s3_copy_utility.py
- tests/sdk/python/rtdip_sdk/data_models/storage_objects/test_utils.py
- tests/sdk/python/rtdip_sdk/pipelines/utilities/aws/test_s3_copy_utility.py
S3 to S3,  Local to S3 and S3 to local copy utility
> Feature/00332 S3 Utilities

- docs/domains/smart_meter/data_model.md
- docs/domains/smart_meter/overview.md
- docs/domains/weather/overview.md
- mkdocs.yml
> Meter Forecasting Energy Domain Specific Preamble

- .github/workflows/sonarcloud_reusable.yml
- .github/workflows/test.yml
> Revert "Support for Spark 3.5.0" - Delta support not available

- setup.py
> Revert "Fix for Pydantic Import"

- environment.yml
- src/api/requirements.txt
> Update jinja package

- environment.yml
- src/api/requirements.txt
> Update asyncio package

- environment.yml
- src/sdk/python/rtdip_sdk/queries/time_series/_time_series_query_builder.py
Resolves issue with `to_json` parameter on the resample query
> Interpolation API Query Fix

- environment.yml
- src/api/requirements.txt
> Update Fastapi version
